import Head from "next/head";
import { Home } from "../components";

export default function Index() {
  return (
    <>
      <Head>
        <title>Google Flights Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Home />
      </div>
    </>
  );
}
